global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'hiring-portal-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['hiring-portal-app:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']